# Generated by Django 5.2 on 2025-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='processing_method',
            field=models.CharField(default='script', max_length=20),
        ),
        migrations.AddField(
            model_name='visualization',
            name='visualization_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
